"use client"

import type React from "react"

import { useState, useEffect } from "react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Search, Plus, Minus, Trash2, ShoppingCart, ChevronDown, ChevronUp, Wifi, WifiOff } from "lucide-react"
import { getProducts, createSale, searchProducts } from "@/lib/database"
import type { Product } from "@/lib/database-types"
import { toast } from "sonner"
import { useAuth } from "@/contexts/auth-context"
import { useOnlineStatus } from "@/hooks/use-online-status"

interface NewSaleFormProps {
  onClose: () => void
  onSuccess?: () => void
}

interface CartItem {
  id: string
  name: string
  unitPrice: number
  quantity: number
  totalPrice: number
  unit: string
}

export function NewSaleForm({ onClose, onSuccess }: NewSaleFormProps) {
  const { user } = useAuth()
  const { isOnline } = useOnlineStatus()
  const [searchTerm, setSearchTerm] = useState("")
  const [cart, setCart] = useState<CartItem[]>([])
  const [paymentMethod, setPaymentMethod] = useState("mpesa")
  const [saleStatus, setSaleStatus] = useState<'completed' | 'pending'>('completed')
  const [products, setProducts] = useState<Product[]>([])
  const [customerName, setCustomerName] = useState("Walk-in Customer")
  const [customerPhone, setCustomerPhone] = useState("")
  const [isLoading, setIsLoading] = useState(false)
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [showAdvanced, setShowAdvanced] = useState(false)

  useEffect(() => {
    loadProducts()
  }, [])

  const loadProducts = async () => {
    try {
      setIsLoading(true)
      const productsData = await getProducts()
      setProducts(productsData)
    } catch (error) {
      console.error("Failed to load products:", error)
      toast.error("Failed to load products")
    } finally {
      setIsLoading(false)
    }
  }

  // Filter products based on search
  const filteredProducts = products.filter(
    (product) => product.name.toLowerCase().includes(searchTerm.toLowerCase()),
  )

  const addToCart = (product: Product) => {
    // Prevent adding out-of-stock products
    if (product.stock_quantity <= 0) {
      toast.error(`${product.name} is out of stock`)
      return
    }

    const existingItem = cart.find((item) => item.id === product.id)

    if (existingItem) {
      if (existingItem.quantity < product.stock_quantity) {
        setCart(
          cart.map((item) =>
            item.id === product.id
              ? { ...item, quantity: item.quantity + 1, totalPrice: (item.quantity + 1) * item.unitPrice }
              : item,
          ),
        )
      }
    } else {
      setCart([
        ...cart,
        {
          id: product.id,
          name: product.name,
          unitPrice: product.unit_price,
          quantity: 1,
          totalPrice: product.unit_price,
          unit: product.unit,
        },
      ])
    }
    // Clear search term after adding product to allow searching for more
    setSearchTerm("")
  }

  const updateQuantity = (id: string, newQuantity: number) => {
    const product = products.find((p) => p.id === id)
    if (!product) return

    if (newQuantity <= 0) {
      setCart(cart.filter((item) => item.id !== id))
    } else if (newQuantity <= product.stock_quantity) {
      setCart(
        cart.map((item) =>
          item.id === id ? { ...item, quantity: newQuantity, totalPrice: newQuantity * item.unitPrice } : item,
        ),
      )
    }
  }

  const removeFromCart = (id: string) => {
    setCart(cart.filter((item) => item.id !== id))
  }

  const total = cart.reduce((sum, item) => sum + item.totalPrice, 0)

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (cart.length === 0 || !user) return

    // Prevent creating pending sales with zero amount
    if (saleStatus === 'pending' && total <= 0) {
      toast.error("Cannot create pending sale with zero amount")
      return
    }

    setIsSubmitting(true)
    try {
      // Create sale data (sale_number will be auto-generated by database)
      const saleData = {
        sale_number: '',
        customer_name: customerName,
        customer_phone: customerPhone || null,
        total_amount: total,
        tax_amount: 0,
        payment_method: paymentMethod as 'cash' | 'mpesa',
        status: saleStatus,
        user_id: user.id,
      }

      // Create sale items data
      const saleItemsData = cart.map(item => ({
        product_id: item.id,
        quantity: item.quantity,
        unit_price: item.unitPrice,
        total_price: item.totalPrice,
      }))

      await createSale(saleData, saleItemsData)

      if (!isOnline) {
        toast.success("Sale saved offline - will sync when internet returns")
      } else if (saleStatus === 'completed') {
        toast.success("Sale completed successfully!")
      } else {
        toast.success("Sale created as pending - debtor record automatically created!")
      }
      if (onSuccess) onSuccess()
      onClose()
    } catch (error) {
      console.error("Failed to create sale:", error)
      toast.error("Failed to complete sale")
    } finally {
      setIsSubmitting(false)
    }
  }

  return (
    <div className="w-full">
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle>Process Sale</CardTitle>
              <CardDescription>Add products and complete the transaction</CardDescription>
            </div>
            <div className={`flex items-center gap-2 px-3 py-1.5 rounded-full text-sm font-medium ${
              isOnline
                ? 'bg-green-100 text-green-700 dark:bg-green-900/20 dark:text-green-400'
                : 'bg-orange-100 text-orange-700 dark:bg-orange-900/20 dark:text-orange-400'
            }`}>
              {isOnline ? (
                <>
                  <Wifi className="h-4 w-4" />
                  <span>Online</span>
                </>
              ) : (
                <>
                  <WifiOff className="h-4 w-4" />
                  <span>Offline</span>
                </>
              )}
            </div>
          </div>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleSubmit} className="space-y-6">
            {/* Product Search & Selection */}
            <div className="space-y-4">
              <div className="relative">
                <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 xl:h-6 xl:w-6 text-muted-foreground" />
                <Input
                  placeholder="Search products..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className="pl-10 xl:h-14 xl:text-lg xl:pl-12"
                />
              </div>

              {/* Show search results or placeholder */}
              {isLoading ? (
                <div className="p-4 text-center text-muted-foreground">
                  Loading products...
                </div>
              ) : searchTerm ? (
                filteredProducts.length > 0 ? (
                  <div className="space-y-2">
                    {filteredProducts.slice(0, 3).map((product) => {
                      const isOutOfStock = product.stock_quantity <= 0
                      return (
                        <div
                          key={product.id}
                          className={`flex items-center justify-between p-3 xl:p-5 border xl:rounded-lg ${
                            isOutOfStock
                              ? 'bg-muted/30 border-muted cursor-not-allowed opacity-60'
                              : 'hover:bg-muted/50 cursor-pointer'
                          }`}
                          onClick={() => addToCart(product)}
                        >
                          <div className="flex-1">
                            <div className={`font-medium xl:text-xl ${isOutOfStock ? 'text-muted-foreground' : ''}`}>
                              {product.name}
                              {isOutOfStock && <span className="text-destructive ml-2 text-sm xl:text-base">(Out of Stock)</span>}
                            </div>
                            <div className="text-sm xl:text-lg text-muted-foreground">
<span className="number-primary">KSh {Math.round(product.unit_price).toLocaleString()}</span> • Stock: {product.stock_quantity} {product.unit}
                            </div>
                          </div>
                          <Button
                            type="button"
                            size="sm"
                            variant="ghost"
                            disabled={isOutOfStock}
                            className="xl:h-12 xl:w-12"
                          >
                            <Plus className="h-4 w-4 xl:h-6 xl:w-6" />
                          </Button>
                        </div>
                      )
                    })}
                  </div>
                ) : (
                  <div className="text-center py-4 text-muted-foreground">No products found matching &quot;{searchTerm}&quot;</div>
                )
              ) : (
                <div className="text-center py-4 text-muted-foreground">
                  Type to search for products...
                </div>
              )}
            </div>

            {/* Selected Products (Inline Cart) */}
            {cart.length > 0 && (
              <div className="space-y-3">
                <h3 className="font-medium">Selected Products</h3>
                <div className="grid gap-2">
                  {cart.map((item) => (
                    <div key={item.id} className="grid grid-cols-1 lg:grid-cols-[1fr_auto_auto] gap-3 p-3 border bg-muted/20">
                      <div className="flex-1 min-w-0">
                        <div className="font-medium truncate">{item.name}</div>
                        <div className="text-sm text-muted-foreground"><span className="number-primary">KSh {Math.round(item.unitPrice).toLocaleString()}</span> each</div>
                      </div>
                      <div className="flex items-center gap-2 justify-center">
                        <Button type="button" size="sm" variant="ghost" onClick={() => updateQuantity(item.id, item.quantity - 1)}>
                          <Minus className="h-3 w-3" />
                        </Button>
                        <Input
                          type="number"
                          min="1"
                          value={item.quantity}
                          onChange={(e) => {
                            const newQuantity = parseInt(e.target.value) || 1
                            updateQuantity(item.id, newQuantity)
                          }}
                          className="w-16 h-8 text-center font-medium"
                        />
                        <Button type="button" size="sm" variant="ghost" onClick={() => updateQuantity(item.id, item.quantity + 1)}>
                          <Plus className="h-3 w-3" />
                        </Button>
                        <Button type="button" size="sm" variant="ghost" onClick={() => removeFromCart(item.id)}>
                          <Trash2 className="h-3 w-3" />
                        </Button>
                      </div>
                      <div className="text-right font-medium lg:min-w-[100px] number-primary">
                        KSh {Math.round(item.totalPrice).toLocaleString()}
                      </div>
                    </div>
                  ))}
                </div>
                
                <div className="flex justify-between text-lg font-bold pt-2 border-t">
                  <span>Total:</span>
                  <span className="number-highlight">KSh {Math.round(total).toLocaleString()}</span>
                </div>
              </div>
            )}

            {/* Payment Method */}
            <div className="space-y-2">
              <Label htmlFor="paymentMethod">Payment Method</Label>
              <Select value={paymentMethod} onValueChange={setPaymentMethod}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="mpesa">M-Pesa</SelectItem>
                  <SelectItem value="cash">Cash</SelectItem>
                </SelectContent>
              </Select>
            </div>

            {/* Advanced Options (Collapsible) */}
            <div className="border">
              <button
                type="button"
                className="flex items-center justify-between w-full p-3 text-left hover:bg-muted/50"
                onClick={() => setShowAdvanced(!showAdvanced)}
              >
                <span className="font-medium">Advanced Options</span>
                {showAdvanced ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}
              </button>
              
              {showAdvanced && (
                <div className="p-3 border-t space-y-4">
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="space-y-2">
                      <Label htmlFor="customerName">Customer Name</Label>
                      <Input
                        id="customerName"
                        value={customerName}
                        onChange={(e) => setCustomerName(e.target.value)}
                        placeholder="Enter customer name"
                      />
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="customerPhone">Customer Phone (Optional)</Label>
                      <Input
                        id="customerPhone"
                        value={customerPhone}
                        onChange={(e) => setCustomerPhone(e.target.value)}
                        placeholder="Enter phone number"
                      />
                    </div>
                  </div>
                  
                  <div className="space-y-2">
                    <Label htmlFor="saleStatus">Sale Status</Label>
                    <Select value={saleStatus} onValueChange={(value) => setSaleStatus(value as 'completed' | 'pending')}>
                      <SelectTrigger>
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="completed">Complete Sale (Payment Received)</SelectItem>
                        <SelectItem value="pending">Pending Payment (Create Debtor)</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                  
                  {saleStatus === 'pending' && (
                    <div className="p-3 bg-yellow-50 border border-yellow-200">
                      <div className="flex items-start">
                        <div className="flex-shrink-0">
                          <svg className="h-5 w-5 text-yellow-400" viewBox="0 0 20 20" fill="currentColor">
                            <path fillRule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clipRule="evenodd" />
                          </svg>
                        </div>
                        <div className="ml-3">
                          <h3 className="text-sm font-medium text-yellow-800">
                            Credit Sale - Debtor Record Will Be Created
                          </h3>
                          <div className="mt-2 text-sm text-yellow-700">
                            <p>This sale will be marked as pending and a debtor record will be automatically created. Stock will not be deducted until payment is completed.</p>
                          </div>
                        </div>
                      </div>
                    </div>
                  )}
                </div>
              )}
            </div>

            {/* Action Buttons */}
            <div className="flex justify-end gap-3 pt-4">
              <Button type="button" variant="outline" onClick={onClose} disabled={isSubmitting} className="xl:h-14 xl:text-lg xl:px-8">
                Cancel
              </Button>
              <Button type="submit" disabled={cart.length === 0 || isSubmitting} className="xl:h-14 xl:text-lg xl:px-8">
                {isSubmitting ? "Processing..." : saleStatus === 'completed'
                  ? <span>Complete Sale - <span className="number-primary">KSh {Math.round(total).toLocaleString()}</span></span>
                  : <span>Create Pending Sale - <span className="number-primary">KSh {Math.round(total).toLocaleString()}</span></span>
                }
              </Button>
            </div>
          </form>
        </CardContent>
      </Card>
    </div>
  )
}
